'use client';

import { useEffect, useMemo, useState } from 'react';
import {
  Accessibility, Activity, AlertTriangle, ArrowLeft, ArrowRight, AudioLines, BadgeCheck,
  Check, ChevronRight, CircleHelp, ClipboardList, FileScan, HeartPulse, Languages,
  LifeBuoy, LockKeyhole, Mic, Pause, Play, RefreshCcw, ScanLine, Settings2, ShieldCheck,
  Stethoscope, UserRound, UsersRound, Volume2, Wifi, WifiOff, X, UploadCloud, Clock3,
  Pencil, Eye, Siren, Database, LogOut, Menu, Baby, Leaf, History, Hospital
} from 'lucide-react';

const API = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000';
type Lang='English'|'हिन्दी'|'ਪੰਜਾਬੀ'|'मराठी'|'தமிழ்'|'తెలుగు'|'ગુજરાતી'|'বাংলা';
type Role='patient'|'doctor'|'triage'|'admin';
type Step='Identify'|'Converse'|'Scan'|'Summarize'|'Consult';

const languages: Lang[]=['English','हिन्दी','ਪੰਜਾਬੀ','मराठी','தமிழ்','తెలుగు','ગુજરાતી','বাংলা'];
const steps:Step[]=['Identify','Converse','Scan','Summarize','Consult'];
const complaints=[
  {id:'Chest pain',icon:'❤️',hint:'Pain or pressure in chest'},
  {id:'Fever',icon:'🌡️',hint:'Fever, chills or body ache'},
  {id:'Headache',icon:'🤕',hint:'Head or facial pain'},
  {id:'Injury',icon:'🩹',hint:'Fall, cut or other injury'},
  {id:'Cough / cold',icon:'🤧',hint:'Cough, cold or throat problem'},
  {id:'Abdominal pain',icon:'🤢',hint:'Stomach or belly pain'},
];
const questionBank:Record<string,string[]>={
 'Chest pain':['When did it start?','Where exactly is the discomfort?','What does it feel like?','Does it spread to the arm, jaw, shoulder or back?','What makes it worse or better?','How severe is it from 0 to 10?','Any breathing difficulty, sweating, nausea or dizziness?'],
 'Fever':['When did the fever start?','What was the highest temperature, if known?','Did it start suddenly or gradually?','Any chills, body ache or rash?','Any cough, throat pain, loose motions or burning while passing urine?','Have you taken any medicine?'],
 'Headache':['When did the headache start?','Where does it hurt?','Is it sudden or gradual?','How severe is it from 0 to 10?','Any vomiting, vision change, weakness, confusion or fainting?','What makes it better or worse?'],
 'Injury':['When and how did the injury happen?','Which body part is injured?','Is there bleeding or an open wound?','Can you move the area normally?','How severe is the pain from 0 to 10?','Did you lose consciousness?'],
 'Cough / cold':['When did it start?','Is there fever?','Is there shortness of breath?','Is the cough dry or with mucus?','Any chest pain or blood in mucus?','Have you taken any medicine?'],
 'Abdominal pain':['When did it start?','Where exactly is the pain?','Is it constant or does it come and go?','How severe is it from 0 to 10?','Any vomiting, loose motions, constipation or blood?','Does food change the pain?'],
};
const bodyParts=['Head','Eyes','Ear','Nose','Throat','Chest','Abdomen','Back','Arm','Hand','Hip','Leg','Knee','Foot','Other'];
const demoPatients=[
 {name:'Demo Patient A',age:68,sex:'F',language:'हिन्दी',complaint:'Fever',type:'Elderly rural'},
 {name:'Demo Patient B',age:32,sex:'M',language:'ਪੰਜਾਬੀ',complaint:'Chest pain',type:'Red flag'},
 {name:'Demo Patient C',age:27,sex:'F',language:'मराठी',complaint:'Headache',type:'Multilingual'},
 {name:'Demo Patient D',age:41,sex:'M',language:'English',complaint:'Abdominal pain',type:'Returning'},
];

const translations:Record<string,any>={
 English:{welcome:'Namaste! Let’s prepare your medical history.',startVoice:'Start with Voice',startTouch:'Answer by Touch',caregiver:'Patient + Caregiver',access:'Accessibility',lang:'Change Language',assist:'I Need Assistance',identify:'Tell us what brought you to the hospital',complaint:'What problem are you having today?',continue:'Continue',back:'Back',repeat:'Repeat question',speak:'Speak your answer',dontknow:"I don’t know",skip:'Skip',scan:'Scan previous medical documents',upload:'Upload prescription or report',ocr:'Digitizing document',summary:'Review your clinical history',confirm:'Is this summary correct?',yes:'Yes, continue',correct:'Correct something',consult:'Ready for clinician review',submit:'Submit & clear session',consent:'I consent to digital clinical history processing',ai:'AI assists. Doctor decides.',red:'Potential emergency symptoms detected',urgent:'Please alert the triage nurse/clinician now.',body:'Where is the problem located?',ayush:'AYUSH / Ayurveda mode',offline:'Offline mode',online:'Connected',doctor:'Doctor view',triage:'Triage',admin:'Hospital admin'},
 'हिन्दी':{welcome:'नमस्ते! आइए आपका मेडिकल इतिहास तैयार करते हैं।',startVoice:'आवाज़ से शुरू करें',startTouch:'टच से जवाब दें',caregiver:'मरीज़ + देखभालकर्ता',access:'सुगम्यता',lang:'भाषा बदलें',assist:'मुझे सहायता चाहिए',identify:'हमें बताएं कि आप अस्पताल क्यों आए हैं',complaint:'आज आपको क्या परेशानी है?',continue:'आगे बढ़ें',back:'वापस',repeat:'सवाल दोहराएँ',speak:'अपना जवाब बोलें',dontknow:'पता नहीं',skip:'छोड़ें',scan:'पुराने मेडिकल दस्तावेज़ स्कैन करें',upload:'पर्ची या रिपोर्ट अपलोड करें',ocr:'दस्तावेज़ पढ़ा जा रहा है',summary:'अपना मेडिकल सारांश देखें',confirm:'क्या यह सारांश सही है?',yes:'हाँ, आगे बढ़ें',correct:'कुछ बदलें',consult:'डॉक्टर की समीक्षा के लिए तैयार',submit:'जमा करें और सत्र साफ करें',consent:'मैं डिजिटल मेडिकल इतिहास प्रोसेसिंग की सहमति देता/देती हूँ',ai:'AI सहायता करता है। फैसला डॉक्टर का है।',red:'संभावित आपातकालीन लक्षण मिले',urgent:'कृपया अभी ट्रायेज नर्स/डॉक्टर को बताएं।',body:'समस्या शरीर के किस हिस्से में है?',ayush:'आयुष / आयुर्वेद मोड',offline:'ऑफलाइन मोड',online:'कनेक्टेड',doctor:'डॉक्टर व्यू',triage:'ट्रायेज',admin:'अस्पताल एडमिन'}
};

function useSpeech(lang:Lang,onText:(text:string)=>void){
 const [listening,setListening]=useState(false);
 const start=()=>{const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!SR){onText('Speech recognition unavailable — use touch options.');return;}const r=new SR();r.lang=lang==='हिन्दी'?'hi-IN':'en-IN';r.interimResults=false;r.onstart=()=>setListening(true);r.onend=()=>setListening(false);r.onerror=()=>setListening(false);r.onresult=(e:any)=>onText(e.results[0][0].transcript);r.start();};
 return {listening,start};
}
function speak(text:string,lang:Lang){if(typeof window==='undefined'||!(window as any).speechSynthesis)return;const u=new SpeechSynthesisUtterance(text);u.lang=lang==='हिन्दी'?'hi-IN':'en-IN';u.rate=.86;speechSynthesis.cancel();speechSynthesis.speak(u);}

export default function Home(){
 const [role,setRole]=useState<Role>('patient');
 const [lang,setLang]=useState<Lang>('English');
 const [step,setStep]=useState<Step>('Identify');
 const [complaint,setComplaint]=useState('');
 const [body,setBody]=useState('');
 const [answers,setAnswers]=useState<Record<string,string>>({});
 const [qIndex,setQIndex]=useState(0);
 const [voiceMode,setVoiceMode]=useState(false);
 const [caregiver,setCaregiver]=useState(false);
 const [senior,setSenior]=useState(false);
 const [ayush,setAyush]=useState(false);
 const [consent,setConsent]=useState(false);
 const [redFlags,setRedFlags]=useState<string[]>([]);
 const [file,setFile]=useState<File|null>(null);
 const [doc,setDoc]=useState<any>(null);
 const [summary,setSummary]=useState<any>(null);
 const [online,setOnline]=useState(true);
 const [assist,setAssist]=useState(false);
 const [abha,setAbha]=useState('');
 const [authenticated,setAuthenticated]=useState(false);
 const [sessionId,setSessionId]=useState('demo-session');
 const [showSettings,setShowSettings]=useState(false);
 const [demo,setDemo]=useState(false);
 const [toast,setToast]=useState('');
 const [editing,setEditing]=useState(false);
 const [submitted,setSubmitted]=useState(false);
 const t=translations[lang]||translations.English;
 const qs=questionBank[complaint]||questionBank['Fever'];
 const q=qs[qIndex];
 const speech=useSpeech(lang,(text)=>{setAnswers(a=>({...a,[q]:text}));detect(text);});
 useEffect(()=>{const f=()=>setOnline(navigator.onLine);f();window.addEventListener('online',f);window.addEventListener('offline',f);return()=>{window.removeEventListener('online',f);window.removeEventListener('offline',f)}},[]);
 useEffect(()=>{if(toast){const x=setTimeout(()=>setToast(''),2800);return()=>clearTimeout(x)}},[toast]);
 const progress=steps.indexOf(step);
 function detect(text:string){const hits:string[]=[];if(/chest pain|pressure.*chest|severe.*breath|difficulty breathing|faint|unconscious|heavy bleeding|one side.*weak|slurred speech|seizure/i.test(text))hits.push('Emergency indicator in response');if(/blood.*vomit|vomit.*blood|blood.*stool/i.test(text))hits.push('Significant bleeding indicator');setRedFlags(h=>Array.from(new Set([...h,...hits])));}
 async function mockAuth(){if(!abha){setToast('Enter a demo ABHA ID, e.g. 12-3456-7890-1234');return;}try{const r=await fetch(API+'/api/abdm/abha/mock-auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({abha_id:abha})});const d=await r.json();setSessionId(d.session_id);setAuthenticated(true);setToast('Mock ABDM sandbox authentication complete');}catch{setAuthenticated(true);setToast('Offline demo authentication enabled');}}
 async function next(){
  if(step==='Identify'){if(!complaint){setToast('Please choose a main complaint.');return;}if(!consent){setToast('Consent is required before digital intake.');return;}setStep('Converse');setQIndex(0);return;}
  if(step==='Converse'){if(qIndex<qs.length-1){setQIndex(i=>i+1);return;}setStep('Scan');return;}
  if(step==='Scan'){if(file){try{const fd=new FormData();fd.append('document',file);const r=await fetch(API+'/api/ocr/mock',{method:'POST',body:fd});setDoc(await r.json());}catch{setDoc({provider:'offline-mock',confidence:.92,entities:{diagnosis:['Fever'],medicines:['Paracetamol 500 mg'],lab_values:[{name:'Hb',value:10.2,unit:'g/dL',reference:'12-16'}],dates:['2026-08-27']},abnormal_flags:['Hb: outside the provided reference range'],timeline:[{date:'2026-08-27',event:'Document digitized'}]});}}setStep('Summarize');await makeSummary();return;}
  if(step==='Summarize'){setStep('Consult');return;}
  if(step==='Consult'){setSubmitted(true);try{await fetch(API+'/api/session/clear',{method:'POST'});}catch{}setToast('Submission complete. Temporary session cleared.');setTimeout(()=>reset(),900);}
 }
 async function makeSummary(){try{const r=await fetch(API+'/api/summary',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({complaint,answers,ayush,document:file?.name})});setSummary(await r.json());}catch{setSummary({chief_complaint:complaint,hpi:Object.entries(answers).map(([k,v])=>`${k}: ${v}`),past_history:'Not provided',past_surgical_history:'Not provided',drug_history:'Not provided',allergy_history:'Not reported',family_history:'Not provided',personal_history:'Not provided',ros:'Not fully assessed',sources:['Patient responses','Demo OCR document'],confidence:{hpi:.91,overall:.89}})}}
 function reset(){setStep('Identify');setComplaint('');setBody('');setAnswers({});setQIndex(0);setRedFlags([]);setFile(null);setDoc(null);setSummary(null);setConsent(false);setAuthenticated(false);setAbha('');setSubmitted(false);}
 function loadDemo(p:any){setLang(p.language as Lang);setComplaint(p.complaint);setConsent(true);setDemo(true);if(p.type==='Red flag'){setRedFlags(['Chest pain + potential emergency pattern']);}setToast(`${p.type} demo loaded`);}
 const historyScore=Math.min(98,62+Object.keys(answers).length*5+(doc?12:0)+(consent?6:0));
 if(role!=='patient')return <Dashboard role={role} onBack={()=>setRole('patient')} redCount={redFlags.length}/>;
 return <div className={'app '+(senior?'senior':'')}>
  <header className="header"><div className="brand"><div className="brandIcon"><HeartPulse size={22}/></div><div><strong>Medi<span>Kiosk</span></strong><small>AI-assisted clinical intake</small></div></div><div className="headerRight"><div className={'network '+(online?'ok':'off')}><span className="dot"/>{online?t.online:t.offline}</div><button className="iconBtn" onClick={()=>setShowSettings(v=>!v)} aria-label="Settings"><Settings2 size={20}/></button><select className="langSelect" value={lang} onChange={e=>setLang(e.target.value as Lang)} aria-label={t.lang}>{languages.map(l=><option key={l}>{l}</option>)}</select></div></header>
  <div className="roleBar"><span><Hospital size={16}/> Hospital Kiosk • OPD</span><div><button onClick={()=>setRole('doctor')}><Stethoscope size={16}/> {t.doctor}</button><button onClick={()=>setRole('triage')}><Siren size={16}/> {t.triage}</button><button onClick={()=>setRole('admin')}><Database size={16}/> {t.admin}</button></div></div>
  {showSettings&&<div className="settingsPanel"><div><b>Accessibility</b><span>Large controls</span></div><label><input type="checkbox" checked={senior} onChange={e=>setSenior(e.target.checked)}/> Senior citizen mode</label><label><input type="checkbox" checked={voiceMode} onChange={e=>setVoiceMode(e.target.checked)}/> Voice-first mode</label><label><input type="checkbox" checked={caregiver} onChange={e=>setCaregiver(e.target.checked)}/> Patient + caregiver mode</label><button onClick={()=>{setOnline(v=>!v);setToast('Offline simulation toggled')}}><WifiOff size={16}/> Simulate offline</button></div>}
  <main className="main">
   <div className="stepper">{steps.map((s,i)=><div key={s} className={'stepItem '+(i===progress?'active ':'')+(i<progress?'done':'')}><div className="stepCircle">{i<progress?<Check size={15}/>:i+1}</div><span>{s}</span></div>)}</div>
   {redFlags.length>0&&<div className="redAlert"><div className="redIcon"><Siren/></div><div><strong>{t.red}</strong><p>{t.urgent}</p><small>AI triage signal • clinician verification required • no diagnosis is being made</small></div><button onClick={()=>setRedFlags([])} aria-label="Dismiss"><X/></button></div>}
   <section className="heroCard">
    <div className="heroTop"><div><div className="eyebrow">{step.toUpperCase()} • {t.ai}</div><h1>{step==='Identify'?t.welcome:step==='Converse'?'Let’s understand your symptoms':step==='Scan'?t.scan:step==='Summarize'?t.summary:t.consult}</h1><p>{step==='Identify'?t.identify:step==='Converse'?'One question at a time. You can speak, tap, skip or replay.':step==='Scan'?'Printed and handwritten documents are supported in this demo.':step==='Summarize'?'Every field is editable and carries source/AI provenance.':'The structured history is ready for the clinician.'}</p></div><div className="secureBadge"><ShieldCheck size={18}/><span>Privacy-first<br/><small>auto-clear after submit</small></span></div></div>
    {step==='Identify'&&<Identify {...{t,complaint,setComplaint,body,setBody,consent,setConsent,abha,setAbha,authenticated,mockAuth,voiceMode,setVoiceMode,caregiver,setCaregiver,ayush,setAyush,assist,setAssist}}/>}
    {step==='Converse'&&<Converse {...{t,lang,q,answers,setAnswers,qIndex,qs,speech,detect,body,voiceMode}}/>}
    {step==='Scan'&&<Scan t={t} file={file} setFile={setFile} doc={doc} setDoc={setDoc} onSkip={()=>setStep('Summarize')}/>} 
    {step==='Summarize'&&<Summary t={t} summary={summary} setSummary={setSummary} editing={editing} setEditing={setEditing} historyScore={historyScore} doc={doc} redFlags={redFlags} onSpeak={()=>speak(`You said you have ${complaint}. Please confirm that this history is correct.`,lang)}/>} 
    {step==='Consult'&&<Consult t={t} historyScore={historyScore} redFlags={redFlags} submitted={submitted}/>} 
    <div className="actions">{(step!=='Identify')&&<button className="btn secondary" onClick={()=>{if(step==='Converse'&&qIndex>0)setQIndex(i=>i-1);else setStep(steps[Math.max(0,progress-1)])}}><ArrowLeft/> {t.back}</button>}<div className="actionRight">{step==='Identify'&&<button className="assistBtn" onClick={()=>{setAssist(true);setToast('Staff assistance requested for this kiosk.')}}><LifeBuoy/> {t.assist}</button>}{step==='Converse'&&<button className="btn secondary" onClick={()=>speak(q,lang)}><Volume2/> {t.repeat}</button>}<button className="btn primary" onClick={next}>{step==='Consult'?t.submit:step==='Summarize'?t.yes:t.continue}<ArrowRight/></button></div></div>
   </section>
   <div className="bottomGrid"><div className="miniCard"><div className="miniIcon"><LockKeyhole/></div><div><b>Consent & audit trail</b><p>Granular consent is recorded before voice/scanning. Access is role-controlled in the prototype.</p></div></div><div className="miniCard"><div className="miniIcon"><RefreshCcw/></div><div><b>Offline resilient</b><p>Questionnaire state is designed to survive temporary connectivity loss and retry synchronization.</p></div></div><div className="miniCard"><div className="miniIcon"><BadgeCheck/></div><div><b>Source traceability</b><p>Patient, caregiver, document and AI-structured facts remain distinguishable for physician review.</p></div></div></div>
   {demo&&<div className="demoStrip"><div><b>SIH Demo Mode</b><span>Realistic fictional patients — no real PHI</span></div><select onChange={e=>{const p=demoPatients[Number(e.target.value)];if(p)loadDemo(p)}} defaultValue=""><option value="">Load another demo patient…</option>{demoPatients.map((p,i)=><option key={i} value={i}>{p.type} • {p.name}</option>)}</select></div>}
  </main>
  {assist&&<div className="modal"><div className="modalCard"><div className="modalIcon"><LifeBuoy/></div><h2>Staff assistance requested</h2><p>Kiosk <b>K-1042</b> • Token <b>OPD-217</b></p><p className="muted">A triage/staff alert has been created. Keep the patient at the kiosk.</p><button className="btn primary" onClick={()=>setAssist(false)}>Okay</button></div></div>}
  {toast&&<div className="toast">{toast}</div>}
  <footer><span>Demo environment • Mock ABDM/ASR/OCR/LLM integrations</span><span><ShieldCheck size={14}/> AI output is editable and requires clinician verification</span></footer>
 </div>
}

function Identify(p:any){const {t,complaint,setComplaint,body,setBody,consent,setConsent,abha,setAbha,authenticated,mockAuth,caregiver,setCaregiver,ayush,setAyush}=p;return <div className="identifyLayout"><div><h3>{t.complaint}</h3><div className="complaintGrid">{complaints.map(c=><button key={c.id} className={'complaint '+(complaint===c.id?'selected':'')} onClick={()=>setComplaint(c.id)}><span>{c.icon}</span><div><b>{c.id}</b><small>{c.hint}</small></div>{complaint===c.id&&<Check className="selectedCheck"/>}</button>)}</div><div className="bodyMap"><div className="bodyHeader"><b>{t.body}</b><span>{body||'Optional'}</span></div><div className="bodyChips">{bodyParts.map(x=><button className={body===x?'on':''} onClick={()=>setBody(x)} key={x}>{x}</button>)}</div></div></div><aside className="sideStack"><div className="modeCard"><div className="modeIcon"><Mic/></div><div><b>Voice-first / Zero Literacy</b><p>Questions can be spoken aloud. No typing required.</p></div><button className="tinyPlay" onClick={()=>speak(t.welcome,'English')}><Play size={15}/></button></div><label className="checkRow"><input type="checkbox" checked={caregiver} onChange={e=>setCaregiver(e.target.checked)}/><UsersRound/> {t.caregiver}</label><label className="checkRow"><input type="checkbox" checked={ayush} onChange={e=>setAyush(e.target.checked)}/><Leaf/> {t.ayush}</label><div className="abha"><div className="abhaTitle"><ShieldCheck/> Mock ABHA / ABDM</div><div className="abhaRow"><input value={abha} onChange={e=>setAbha(e.target.value)} placeholder="12-3456-7890-1234"/><button onClick={mockAuth}>{authenticated?'✓ Authenticated':'Verify'}</button></div><small>Sandbox only — no government API call is faked.</small></div><label className="consentBox"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span><b>Consent</b><br/><small>{t.consent}. I understand this is an AI-assisted intake and the doctor makes clinical decisions.</small></span></label></aside></div>}

function Converse(p:any){const {t,lang,q,answers,setAnswers,qIndex,qs,speech,detect,body,voiceMode}=p;const answer=answers[q]||'';return <div className="conversation"><div className="questionPanel"><div className="questionMeta"><span>Question {qIndex+1} of {qs.length}</span><span>{body?`Body area: ${body}`:''}</span></div><h2>{q}</h2><div className="voiceZone"><button className={'voiceButton '+(speech.listening?'listen':'')} onClick={speech.start}><Mic size={32}/></button><b>{speech.listening?'Listening…':t.speak}</b><small>Web Speech API • Bhashini adapter available in backend</small></div><div className="answerBox">{answer||'Your answer will appear here…'}</div></div><div className="quickAnswers"><h3>Quick answers</h3><div className="answerGrid">{['Yes','No','Mild','Moderate','Severe','Not sure'].map(x=><button className={answer===x?'selected':''} onClick={()=>{setAnswers((a:any)=>({...a,[q]:x}));detect(x)}} key={x}>{x}</button>)}</div><div className="textFallback"><input aria-label="Optional answer" value={answer} onChange={e=>{setAnswers((a:any)=>({...a,[q]:e.target.value}));detect(e.target.value)}} placeholder="Optional: type or correct your answer"/><button onClick={()=>setAnswers((a:any)=>({...a,[q]:t.dontknow}))}>{t.dontknow}</button><button onClick={()=>setAnswers((a:any)=>({...a,[q]:t.skip}))}>{t.skip}</button></div></div></div>}

function Scan({t,file,setFile,doc,setDoc,onSkip}:any){return <div className="scanArea"><div className="dropZone"><FileScan size={52}/><h2>{file?file.name:t.upload}</h2><p>Prescription • blood report • discharge summary • imaging report</p><label className="btn primary"><UploadCloud/> Choose file<input hidden type="file" accept="image/*,.pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><small>OCR pipeline: preprocess → OCR → medical entities → confidence → verification → timeline</small></div><div className="docPreview"><div className="docHead"><b>Document intelligence</b><span className="tag">Mock provider</span></div>{file?<div className="processing"><div className="scanAnim"><ScanLine/></div><b>{t.ocr}</b><p>Entity extraction will surface medicines, diagnoses, labs and dates.</p><div className="docRows"><span>OCR confidence</span><b>92%</b><span>Handwriting</span><b>Supported (mock)</b><span>Languages</span><b>Multilingual adapter</b></div></div>:<div className="emptyDoc"><ScanLine/><p>Upload a document to see extracted evidence and abnormal-value flags.</p></div>}<button className="linkBtn" onClick={onSkip}>Skip documents →</button></div></div>}

function Summary({t,summary,setSummary,editing,setEditing,historyScore,doc,redFlags,onSpeak}:any){const fields=[['Chief Complaint','chief_complaint'],['History of Present Illness','hpi'],['Past Medical History','past_history'],['Past Surgical History','past_surgical_history'],['Drug History','drug_history'],['Allergy History','allergy_history'],['Family History','family_history'],['Personal History','personal_history'],['Review of Systems','ros']];return <div className="summaryArea"><div className="scoreCard"><div><span>History completeness</span><strong>{historyScore}%</strong></div><div className="scoreBar"><i style={{width:`${historyScore}%`}}/></div><small>Generated from answered fields, document availability and consent. Score is an intake completeness signal, not a medical quality grade.</small></div>{redFlags.length>0&&<div className="summaryRed"><Siren/><div><b>Red-flag review required</b><span>{redFlags.join(' • ')}</span></div></div>}<div className="summaryHeader"><div><h3>Physician-ready structured history</h3><p>AI-structured • editable • source-traceable</p></div><div><button className="btn secondary" onClick={()=>setEditing(v=>!v)}><Pencil/> {editing?'Done':'Edit all'}</button><button className="btn secondary" onClick={onSpeak}><Volume2/> Patient confirmation</button></div></div><div className="fields">{fields.map(([label,key])=><div className="field" key={key}><div className="fieldHead"><b>{label}</b><span className="source">{key==='hpi'?'Patient reported':key.includes('history')?'Not reported / AI structured':'AI structured'}</span></div>{editing?<textarea value={typeof summary?.[key]==='string'?summary[key]:(summary?.[key]||[]).join('\n')} onChange={e=>setSummary((s:any)=>({...s,[key]:e.target.value}))}/>:<div className="fieldValue">{typeof summary?.[key]==='string'?summary[key]:(summary?.[key]||[]).map((x:string,i:number)=><div key={i}>{x}</div>)}</div>}<small>Confidence: {summary?.confidence?.[key]?(Math.round(summary.confidence[key]*100)+'%'):'91%'} • Verify before clinical use</small></div>)}</div>{doc&&<Timeline doc={doc}/>}<div className="bilingual"><div><Languages/><b>Patient language</b><span>Hindi / selected language</span></div><ChevronRight/><div><Stethoscope/><b>Doctor display</b><span>English clinical structure</span></div></div></div>}
function Timeline({doc}:any){return <div className="timeline"><div className="timelineTitle"><History/><b>Medical timeline</b><span>Source documents openable by clinician</span></div>{(doc.timeline||[{date:'2026-08-27',event:'Document digitized'}]).map((e:any,i:number)=><div className="timelineItem" key={i}><div className="date">{e.date}</div><div className="event"><b>{e.event}</b><span>Source: uploaded document • confidence 92%</span></div></div>)}{doc.entities?.lab_values?.map((l:any,i:number)=><div className="timelineItem" key={'lab'+i}><div className="date">Lab</div><div className="event"><b>{l.name}: {l.value} {l.unit}</b><span className="abnormal">{doc.abnormal_flags?.[i]||'Check reference range'} • Reference {l.reference}</span></div></div>)}</div>}
function Consult({t,historyScore,redFlags,submitted}:any){return <div className="consult"><div className="consultIcon"><Stethoscope/></div><h2>{submitted?'Session cleared':'Ready for clinician review'}</h2><p>{submitted?'Temporary kiosk session data has been cleared.':'The doctor receives the structured history, timeline, source provenance and any triage alerts.'}</p><div className="consultStats"><div><b>{historyScore}%</b><span>Completeness</span></div><div><b>{redFlags.length?'RED':'GREEN'}</b><span>Triage signal</span></div><div><b>FHIR</b><span>HIS-ready layer</span></div></div><div className="doctorNotice"><ShieldCheck/><span><b>AI assists. Doctor decides.</b><br/>No autonomous diagnosis or treatment recommendation is produced.</span></div></div>}

function Dashboard({role,onBack,redCount}:{role:Role,onBack:()=>void,redCount:number}){const [filter,setFilter]=useState('All');const title=role==='doctor'?'Physician Dashboard':role==='triage'?'Real-time Triage':'Hospital Operations';const queue=[{token:'K-1042',patient:'Demo Patient A',complaint:'Fever',priority:'GREEN',status:'Ready for doctor',time:'09:42'},{token:'K-1043',patient:'Demo Patient B',complaint:'Chest pain',priority:'RED',status:'Immediate attention',time:'09:44'},{token:'K-1044',patient:'Demo Patient C',complaint:'Headache',priority:'YELLOW',status:'Needs clarification',time:'09:47'},{token:'K-1045',patient:'Demo Patient D',complaint:'Abdominal pain',priority:'GREEN',status:'History complete',time:'09:49'}];return <div className="dashboardPage"><header className="dashHeader"><div className="brand"><div className="brandIcon"><HeartPulse/></div><div><strong>Medi<span>Kiosk</span></strong><small>{title}</small></div></div><button className="btn secondary" onClick={onBack}><LogOut/> Patient kiosk</button></header><main className="dashMain"><div className="dashTitle"><div><div className="eyebrow">HOSPITAL WORKSPACE</div><h1>{title}</h1><p>Prototype dashboard with role-based visibility and auditable clinical intake signals.</p></div><div className="live"><span/> Live updates</div></div><div className="metricGrid"><Metric icon={<UsersRound/>} label="Patients processed" value="128" delta="+18 today"/><Metric icon={<Clock3/>} label="Avg intake" value="4m 12s" delta="−21% vs baseline"/><Metric icon={<Siren/>} label="Priority alerts" value={String(3+redCount)} delta="2 awaiting acknowledgement"/><Metric icon={<ClipboardList/>} label="Incomplete histories" value="9" delta="7% of queue"/></div>{role==='doctor'?<DoctorPanel/>:role==='triage'?<TriagePanel queue={queue}/>:<AdminPanel queue={queue} filter={filter} setFilter={setFilter}/>}</main></div>}
function Metric({icon,label,value,delta}:any){return <div className="metric"><div className="metricIcon">{icon}</div><span>{label}</span><strong>{value}</strong><small>{delta}</small></div>}
function TriagePanel({queue}:any){return <div className="dashGrid"><div className="panel"><div className="panelTitle"><h3><Siren/> Priority queue</h3><span>RED = immediate attention</span></div>{queue.map((x:any)=><div className={'queueRow '+x.priority.toLowerCase()} key={x.token}><div className="queuePriority">{x.priority}</div><div><b>{x.token} • {x.patient}</b><span>{x.complaint} • {x.status}</span></div><time>{x.time}</time><button className="btn smallBtn">Acknowledge</button></div>)}</div><div className="panel alertPanel"><h3>Safety protocol</h3><p>Potential emergency patterns stop the normal questionnaire and alert triage staff. The system does not diagnose.</p><div className="protocol"><Check/> Alert generated</div><div className="protocol"><Check/> Staff acknowledgement</div><div className="protocol"><Check/> Clinical assessment</div></div></div>}
function DoctorPanel(){return <div className="doctorDashboard"><div className="patientHeader"><div className="avatar"><UserRound/></div><div><h2>Demo Patient B</h2><span>Age 32 • Male • Token K-1043 • Punjabi</span></div><div className="redBadge"><Siren/> Priority review</div></div><div className="doctorColumns"><div className="panel"><div className="panelTitle"><h3>Clinical summary</h3><button className="btn secondary"><Pencil/> Edit</button></div>{['Chief Complaint: Chest pain','HPI: Started today; severity reported as moderate','Drug History: Not reported','Allergy History: Missing','Family History: Not provided','ROS: Partial'].map(x=><div className="doctorField" key={x}>{x}<span>source trace</span></div>)}<div className="doctorActions"><button className="btn primary"><BadgeCheck/> Accept reviewed fields</button><button className="btn secondary"><CircleHelp/> Request clarification</button></div></div><div className="panel"><h3>Source traceability</h3><div className="sourceItem"><UserRound/><div><b>Chest pain</b><span>Patient reported • 09:44</span></div><Eye/></div><div className="sourceItem"><FileScan/><div><b>Paracetamol 500 mg</b><span>Prescription • 27 Aug 2026 • OCR 96%</span></div><Eye/></div><div className="sourceItem"><AlertTriangle/><div><b>Potential red flag</b><span>AI triage layer • verify clinically</span></div><Eye/></div><h3 className="mt">Medical timeline</h3><div className="miniTimeline"><b>2026</b><span>27 Aug • Prescription scanned</span><span>29 Aug • Current OPD intake</span></div></div></div></div>}
function AdminPanel({queue,filter,setFilter}:any){return <div className="adminPanel"><div className="panel"><div className="panelTitle"><h3><Hospital/> OPD queue</h3><div className="filters">{['All','RED','YELLOW','GREEN'].map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div></div>{queue.filter((x:any)=>filter==='All'||x.priority===filter).map((x:any)=><div className="queueRow" key={x.token}><div className={'queuePriority '+x.priority.toLowerCase()}>{x.priority}</div><div><b>{x.token} • {x.patient}</b><span>{x.complaint} • {x.status}</span></div><time>{x.time}</time></div>)}</div><div className="analytics"><h3>Operations</h3><div className="barStat"><span>Hindi</span><i style={{width:'72%'}}/><b>72%</b></div><div className="barStat"><span>English</span><i style={{width:'46%'}}/><b>46%</b></div><div className="barStat"><span>Punjabi</span><i style={{width:'28%'}}/><b>28%</b></div><div className="barStat"><span>Documents digitized</span><i style={{width:'81%'}}/><b>81%</b></div><div className="innovation"><Leaf/><div><b>20 SIH innovation features</b><span>Voice-first • body map • adaptive questioning • source traceability • offline • AYUSH • returning-patient flow</span></div></div></div></div>}
